### PR TITLE
ZEN-31325 upgrade PyYAML lib to 5.2

### PR DESCRIPTION
**Pull request by DeKapito**
Upgrade PyYAML to 5.2

The latest PyYAML release is 5.3 with some fixes. Which version do we better upgrade to?

### CODE REVIEW

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by jpeacock-zenoss** [comment]
Have you tested the code with pyyaml 5.3 installed?
I would like us to use the most recent release possible.

**Comment by DeKapito** [comment]
I tested with PyYAML 5.2. I will test 5.3

**Comment by DeKapito** [comment]
Changed PyYAML version from 5.2 to 5.3

**Pull request merged**
